module.exports = {
    formHead: {
        fontSize: 30,
        color: 'white',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    formInput: {
        width: '80%',
        backgroundColor: 'white',
        borderRadius: 10,
        marginVertical: 10,
        paddingHorizontal: 15,
        paddingVertical: 10,
        fontSize: 10,
    },
    formbtn: {
        width: '80%',
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        borderRadius: 10,
        borderColor: 'white',
        borderWidth: 1,
        fontSize: 25, 
        color: 'white',
        textAlign: 'center',
        paddingVertical: 10,
        paddingHorizontal: 10,
    },
    formTextLinkRight: {
        color: 'white',
        fontSize: 15,
        textAlign: 'right',
        width: '80%',
        marginVertical: 10,
    },
    formTextLinkCenter: {
        color: 'white',
        fontSize: 16,
    },
    formHead2: {
        fontSize: 20,
        color: 'white',
        textAlign: 'center',
    },
    formHead2Left: {
        fontSize: 20,
        color: 'white',
        textAlign: 'left',
    },
    formHead3: {
        fontSize: 20,
        color: 'white',
        textAlign: 'center',
        fontWeight: '400',
        padding: 10,
        borderRadius: 10,
        width: '80%',
        marginVertical: 10,
    },
}